server:
  port: 8080
spring:
  datasource:
    name: quaint
    url: jdbc:mysql://127.0.0.1:3306/quaintblog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.qq.com # QQ邮箱smtp主机
    port: 587 #端口号465或587
    username: 857776215@qq.com
    password: arttnyqgipcmbcjg # 这里QQ邮箱开通POP3/SMTP提供的授权码，如果邮箱服务商没有授权码，可以使用密码代替
    protocol: smtp
    default-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.quaint.blogback.pojo
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

